{% set version = "0.3.3" %}
{% set sha256 = "3c577592706860dec1bf7e47529d9a58caeaea6969100980b096ad350e90871c" %}

package:
  name: py_stringsimjoin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/py_stringsimjoin/py_stringsimjoin-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [not x86_64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msinttypes  # [win and vc<14]
  host:
    - python
    - pip
    - setuptools
    - cython
    - pandas
    - six
    - joblib
    - pyprind
    - py_stringmatching
  run:
    - python
    - six
    - pandas >=0.16.0
    - joblib
    - pyprind >=2.9.3
    - py_stringmatching >=0.2.1

test:
  imports:
    - py_stringsimjoin

about:
  home: https://sites.google.com/site/anhaidgroup/projects/py_stringsimjoin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for string similarity joins.
  description: |
    This project seeks to build a Python software package that provides
    scalable implementation of string similarity joins over two tables,
    for commonly used similarity measures such as Jaccard, Dice, cosine,
    overlap, overlap coefficient and edit distance. 
  doc_url: http://anhaidgroup.github.io/py_stringsimjoin/
  dev_url: https://github.com/anhaidgroup/py_stringsimjoin

extra:
  recipe-maintainers:
    - pjmartinkus
