travis:
  secure:
    BINSTAR_TOKEN: clAo5YOcvXaIR9nN6hxKzy2avUJhhB6Xp+J3iA4di+3Q1KAuOmJz+vmb5jN80yxQkG9zsVXDWEa3XIGb0SpoRe6mZM0bjsfe70FEIyPWoPNOZQzlRsejtpQZFezPNydJQGtmHJBfIGbF+xBFpbpz+XnZacwwHhSi+w8LZVw3EberD92qxm+gwfXdzEpFnnKFdoENYvOLG4G9KWspjSR4pNJf/ZF8WUo40h19+bo6tXpLCRA5J/yuYQvh22Pqd1UoNbB3WrhbWCBv+/hllZyhrFVeSHRDwHzWGAkkB/IjJOd+eN5fWQOs3KYjzi/55/dYbdU3Jjwr1jEzxh4tTqsJk88nSz4qGwL4BhD0qRm+YKhH/Tl+qsXbjrs6fS6Zyw8L6orCNqxP9d+ryhdZYxZZW3l1bzo9MV9CYQA3hNO1rh6TBlyJHhXl3wKhOODfdOOkl1Vij9z2Qoq//FSaYY3oXIpJl0KcXyv6j+ca5g1N5y+qzAkE2gSoeFWUE/LQHWrP7kiy41Sb7mSbUpmmmVVm6CxY9wckBzN5xNB1xJz2Xw2XOCuqXbMfF0ConyklmhZXl6y3zk9JIwig1oVDmGQB8E6WCNrw99ghS90WKDkS3iR+U8ji8gCqGWZNb/KUgJGhAaoFpKqmcvOA7+f5dh5XR385p3iXqKJBbS4BYZbxFV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
